version: "3.2"

services:
  #nginx:
    #container_name: nginx
    #image: nginx:latest
    #ports:
    #- "8090:3000"
    #volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/error.log:/etc/nginx/error_log.log
    #restart: always
    #networks:
      #- frontendnet
  backend:
    build:
      context: restaurante-back
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./uploads:/usr/src/uploads/
      - /usr/src/app/node_modules/
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
    networks:
      - backendnet
      - frontendnet

  frontend:
    build:
      context: restaurante
      dockerfile: Dockerfile
      args:
        REACT_APP_HOST_IP_ADDRESS: http://localhost
        REACT_APP_HOST_PORT: 5000
    volumes:
      - ./uploads:/usr/src/uploads/
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - frontendnet
      - backendnet

  mongodb:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    restart: always
    environment:
      - AUTH=no
    volumes:
      - ./data/db:/data/db
    networks:
      - backendnet
      
networks:
  backendnet:
  frontendnet:    
